# Travis configuration

sudo: false

language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

cache:
    directories:
        - $HOME/.composer/cache
  
matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0

install:
    - composer install --no-interaction

script:
#- phpunit -c ./phpunit.xml.dist
- phpunit -c vendor/bin/phpunit